//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by PhotoThing.rc
//
#define IDD_ABOUTBOX                    100
#define IDR_MAINFRAME                   128
#define IDS_IMAGEBACK                   129
#define IDS_IMAGEFORWARD                130
#define IDS_RUN                         131
#define IDS_RESET                       132
#define IDS_DELETE                      133
#define IDS_ROTLEFT                     134
#define IDS_ROTRIGHT                    135
#define IDS_ZOOM                        136
#define IDS_BAR_FILE                    137
#define IDS_BAR_EDIT                    138
#define IDS_BAR_INFO                    139
#define IDS_BAR_PRINT                   140
#define IDS_BAR_EMAIL                   141
#define IDS_BAR_BURN                    142
#define IDS_TREE_PICTURESVIDEOS         143
#define IDS_TREE_PICTURES               144
#define IDS_TREE_VIDEO                  145
#define IDS_TREE_RECENTLYIMPORTED       146
#define IDS_TREE_TAGS                   147
#define IDS_TREE_CREATETAG              148
#define IDS_TREE_NOTTAGGED              149
#define IDS_TREE_RATINGS                150
#define IDS_TREE_NOTRATED               151
#define IDS_TREE_FOLDERS                152
#define IDS_TREE_FOLDER_PICTURE         153
#define IDS_TREE_DATETAKEN              154
#define IDS_TREE_FOLDER_VIDEO           155
#define IDS_TREE_FOLDER_PUBPICTURE      156
#define IDS_TREE_FOLDER_PUBVIDEO        157
#define IDS_SEARCH                      158
#define IDS_NOIMAGES                    159
#define IDS_ADDKEYWORD                  160
#define IDS_KEYWORD_ANIMALS             161
#define IDS_KEYWORD_OCEAN               162
#define IDS_KEYWORD_LANDSCAPES          163
#define IDS_STATUSBAR_SEL               164
#define IDS_STATUSBAR_NOSEL             165
#define IDS_HELP                        166
#define IDS_NAVBACK                     167
#define IDS_NAVFORWARD                  168
#define IDS_BAR_MOVIE                   169
#define IDB_NAVPANEL_LEFT               202
#define IDB_NAVPANEL_RIGHT              206
#define IDB_NAVPANEL_SIDE               207
#define IDB_NAVPANEL_MIDDLE             208
#define IDB_NAVBUTTONS_FORWARD          209
#define IDB_NAVBUTTONS_BACK             210
#define IDB_NAVBUTTONS_RESET            211
#define IDB_NAVBUTTONS_ROTLEFT          212
#define IDB_NAVBUTTONS_ROTRIGHT         213
#define IDB_NAVBUTTONS_RUN              214
#define IDB_NAVBUTTONS_ZOOM             215
#define IDB_NAVBUTTONS_DELETE           216
#define IDB_BAR_RIGHT                   217
#define IDB_BAR_LEFT                    218
#define IDB_BAR_HELP                    219
#define IDB_BAR_CHEVRON                 220
#define IDB_BARBUTTON_RIGHT             221
#define IDB_BARBUTTON_LEFT              222
#define IDB_BARBUTTON_MIDDLE            223
#define IDB_BARITEM_INFO                224
#define IDB_BARITEM_EDIT                225
#define IDB_BARITEM_FILE                226
#define IDB_BARITEM_PRINT               227
#define IDB_BARITEM_BURN                228
#define IDB_BARITEM_EMAIL               229
#define IDB_TREEIMAGES                  230
#define IDB_TREEIMAGES_MASK             231
#define IDB_EMPTY1                      232
#define IDB_EMPTYSELECTION              233
#define IDB_INFOSHADOW                  234
#define IDB_ADDKEYWORD                  235
#define IDB_KEYWORDS                    236
#define IDB_RESET                       238
#define IDB_SEARCH                      240
#define IDB_BARITEM_MOVIE               241
#define IDM_OPTIONS                     242
#define IDM_LISTVIEW                    243
#define IDM_SEARCHALL                   244
#define IDC_NAV_BACK                    2000
#define IDC_NAV_FORWARD                 2001
#define IDC_NAV_RUN                     2002
#define IDC_IMAGE_DELETE                2003
#define IDC_IMAGE_RESET                 2004
#define IDC_IMAGE_ZOOM                  2005
#define IDC_IMAGE_ROTLEFT               2006
#define IDC_IMAGE_ROTRIGHT              2007
#define IDC_IMAGE_BACK                  2008
#define IDC_IMAGE_FORWARD               2009
#define IDC_NAV_HELP                    2010
#define IDC_NAV_CHEVRON                 2011
#define ID_BAR_FILE                     2012
#define ID_BAR_EDIT                     2013
#define ID_BAR_INFO                     2014
#define ID_BAR_PRINT                    2015
#define ID_BAR_EMAIL                    2016
#define ID_BAR_BURN                     2017
#define IDC_TREE                        2018
#define IDC_INFO                        2019
#define IDC_SEARCHFILTER                2020
#define IDC_INFONAME                    2021
#define IDC_INFODATE                    2022
#define IDC_INFOTIME                    2023
#define IDC_INFOSIZE                    2024
#define IDC_ADDKEYWORD                  2025
#define IDC_KEYWORDS                    2025
#define IDC_INFODESCRIPTION             2026
#define IDC_STATUSBAR                   2027
#define IDC_RATING                      2028
#define IDC_SEARCHDROP                  2029
#define ID_BAR_MOVIE                    2030
#define ID_VIEW_THUMBNAILS              32772
#define ID_VIEW_THUMBTEXT               32773
#define ID_VIEW_TILES                   32774
#define ID_GROUPBY_DATE                 32775
#define ID_GROUPBY_TITLE                32776
#define ID_SORTBY_DATE                  32777
#define ID_SORTBY_TEXT                  32778
#define ID_VIEW_CONTENTS                32779
#define ID_VIEW_UPDATE                  32780
#define ID_VIEW_OPTIONS                 32781
#define ID_VIEW_SELECTALL               32783
#define ID_SEARCH_DROPDOWN              32784

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        245
#define _APS_NEXT_COMMAND_VALUE         32785
#define _APS_NEXT_CONTROL_VALUE         1000
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
